mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^tracker/', include('tracker.urls')),
    url(r'^users/', include('users.urls')),

    # forward localhost:8000 to tracker
    url(r'^', include('tracker.urls')),
    url(r'^admin/', admin.site.urls),
]

tracker/urls.py
from django.conf.urls import url

from . import views

app_name = 'tracker'

urlpatterns = [
    # ex: /tracker/
    url(r'^$', views.mainpage_controller, name='mainpage'),
    # ex: /tracker/
    url(r'^styled$', views.mainpage_with_styles, name='mainpage_with_styles'),
    # ex: /tracker/statistics
    url(r'^statistics$', views.statistics, name='statistics'),
    # ex: /tracker/about
    url(r'^about$', views.about, name='about'),
    url(r'^resetdb$', views.resetdb, name='resetdb'),

    # restart habit
    url(r'^habits/(?P<habit_id>[0-9]+)/restart/$', views.restart_habit_controller, name='restart_habit'),
    # drop habit
    url(r'^habits/(?P<habit_id>[0-9]+)/drop/$', views.drop_habit_controller, name='drop_habit'),
    # add habbit
    url(r'^habits$', views.add_habit_controller, name='add_habit'),
    # edit habbit
    url(r'^habits/(?P<habit_id>[0-9]+)/edit$', views.edit_habit_controller, name='edit_habit'),

    # edit record
    url(r'^habits/(?P<habit_id>[0-9]+)/records/(?P<number>[0-9]+)$', views.edit_record_controller, name='edit_record'),

    # show habit
    url(r'^habits/(?P<pk>[0-9]+)$', views.HabitView.as_view(), name='habit_details'),

]

users/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    # resetingdb works from tracker app
    # url(r'^resetdb$', views.resetdb, name='resetdb'),

    # login & logout
    url(r'^login/$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout$', views.log_out, name='logout'),

    # loged in & loged out
    url(r'^loged$', views.loged, name='loged'),
    url(r'^logedout$', views.logedout, name='logedout'),
    url(r'^', include('registration.backends.simple.urls')),

]

tracker/models.py
from django.db import models
from django.contrib.auth.models import User


class Habit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    habit_name = models.CharField(max_length=200)
    repetitions_per_week = models.IntegerField(default=7)
    starting_date = models.DateField('date_started')
    order = models.IntegerField(default=1)

    def __str__(self):
        return self.habit_name + " " + str(self.repetitions_per_week) + " " + self.volume_with_units

    def get_record(self, date):
        record = Record.objects.filter(
            habit=self,
            date__year=date.year,
            date__month=date.month,
            date__day=date.day
        ).first()
        return record


class Record(models.Model):
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE)
    date = models.DateField('date_recorded')

    def __str__(self):
        return self.habit.habit_name + " on " + str(self.date.date())

tracker/forms.py
from django import forms
from django.utils import timezone

class AddHabitForm(forms.Form):
    habit_name = forms.CharField(label='Habit name', max_length=200)
    repetitions_per_week = forms.IntegerField(initial=7)


class ChangeOrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        extra = kwargs.pop('extra')
        super().__init__(*args, **kwargs)

        for habit_id, order in extra:
            self.fields['%s' % habit_id] = forms.IntegerField(initial=order)

    def get_answers(self):
        return self.cleaned_data

tracker/views.py
import operator

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

from .forms import AddHabitForm, ChangeOrderForm
from .models import Habit, Record
from django.contrib.auth.models import User

class RecordValues:
    SUCCESS, FAIL, NO_RECORD = range(3)

DAYS_DISPLAYED = 7
FUTURE_DAYS_DISPLAYED = 4
DEFAULT_USER = "niko"
NEW_HABITS = ["specify your own...",
              "run 5 min",
              "meditate 10 min",
              "eat an apple",
              ]

def now():
    return timezone.now().astimezone().date()


def date_lt(first, second):
    '''
    return True for first date < second date
    :param first:
    :param second:
    :return:
    '''
    if first.year < second.year:
        return True
    else:
        if first.year > second.year:
            return False
    if first.month < second.month:
        return True
    else:
        if first.month > second.month:
            return False
    if first.day < second.day:
        return True
    else:
        if first.day > second.day:
            return False

    return False


class StatisticsItem:
    last_10_days_success_ratio = 0
    total_sucesses = 0
    overall_sucess_ratio = 0
    time_since_start = 0
    habit = None

    def __init__(self, last_10_days_success_ratio,total_sucesses, overall_sucess_ratio, time_since_start, habit):
        self.last_10_days_success_ratio  = last_10_days_success_ratio
        self.total_sucesses = total_sucesses
        self.overall_sucess_ratio = overall_sucess_ratio
        self.time_since_start = time_since_start
        self.habit = habit



@login_required()
def statistics(request):

    user = request.user

    # get all habits
    habits = Habit.objects.filter(user=user).order_by('order')

    # create StatistisItems
    statistics_items = []
    for habit in habits:
        records = habit.record_set.all()

        last_10_days_success_ratio = get_last_n_days_success_ratio(10, records, habit.starting_date)
        total_sucesses = len(records)
        time_since_start = (now() - habit.starting_date) + timezone.timedelta(days=1)
        days_since_start = time_since_start.days
        overall_success_ratio = total_sucesses/days_since_start
        si = StatisticsItem(last_10_days_success_ratio=last_10_days_success_ratio,
                            total_sucesses = total_sucesses,
                            overall_sucess_ratio = overall_success_ratio,
                            time_since_start = time_since_start,
                            habit = habit)
        statistics_items.append(si)

    # send rendering
    user = request.user
    context = {'statistics_items': statistics_items,
               'username': user.username}
    return render(request, 'tracker/statistics.html', context)


def get_last_n_days_success_ratio(n_last_days, records, start_date):
    today = now()
    tomorrow = today + timezone.timedelta(days=1)
    days_since_habit_started = (tomorrow-start_date).days
    n_days_ago = today - timezone.timedelta(days=n_last_days)
    last_10_days_successes = records.filter(date__gt=n_days_ago,
                                           date__lt=tomorrow
                                           )
    success_ratio = 0
    if days_since_habit_started < n_last_days:
        success_ratio = last_10_days_successes.count() / days_since_habit_started
    else:
        success_ratio = last_10_days_successes.count() /n_last_days
    return success_ratio


def about(request):
    context = {}
    return render(request, 'tracker/about.html', context)


def get_records_table(for_habit, n):
    """
    Returns table with SUCCESS/FAIL/NO-RECORD fields for last n days of given habit
    :param for_habit: habit to be analysed
    :param n: number of last days we are interested in
    :return: table with SUCCESS/FAIL/NO-RECORD fields
    """
    today = now()
    tomorrow = today + timezone.timedelta(days=1)
    n_days_ago = today - timezone.timedelta(days=n)

    # find successes in last n days
    successes = Record.objects.filter(
        habit=for_habit,
        date__gt=n_days_ago,
        date__lt=tomorrow
        ).order_by('-date')
    # get dates of successes
    successful_days = [s.date for s in successes]

    # init new table with FAILs for last n days
    table = [RecordValues.FAIL] * n;

    # fill SUCCESSes in the table
    i = n-1
    # iterating last n dates
    start = for_habit.starting_date
    for day in (now() - timezone.timedelta(days=x) for x in range(0, n)):
        if day in successful_days:
            table[i] = RecordValues.SUCCESS;
        else:
            if date_lt(day,start):
                table[i] = RecordValues.NO_RECORD
        i-=1

    return table


def get_speed(record_table):
    """
    Go through given record table and return ratio success:total
    :param record_table: array with SUCCESS/FAIL/NO-RECORD fields
    :return: ration - number of suceess divided by number of tries
    """
    successes = 0
    total = 0
    for entry in record_table:
        if entry == RecordValues.SUCCESS:
            successes += 1
        if entry != RecordValues.NO_RECORD:
            total += 1
    return successes/total


def get_dates(days_displayed):
    iterator = reversed(range(0, days_displayed))
    # lambda function, get dates i.e. [(2016,12,3), (2016,12,4), (2016,12,5), ... , today.date()]
    dates_iterator = (now() - timezone.timedelta(days=x) for x in iterator)
    dates = []
    for d in dates_iterator:
        dates.append(d)
    return dates


def get_future_dates(days_displayed):
    iterator = range(1, days_displayed+1)
    # lambda function, get dates i.e. [today.date()+1, ..., (2016,12,17), (2016,12,18), (2016,12,21)]
    dates_iterator = (now() + timezone.timedelta(days=x) for x in iterator)
    dates = []
    for d in dates_iterator:
        dates.append(d)
    return dates


def reorder_habits(cleaned_data):
    pass


def get_fields(habits):
    ids = []
    for habit in habits:
        id = habit.id
        order = habit.order
        ids.append((id,order))
    return ids


@login_required
def mainpage_controller(request):
    user = request.user

    # get all habits
    habits_list = Habit.objects.filter(user=user).order_by('order')

    # ordering of habits
    form_fields = get_fields(habits_list)
    form = ChangeOrderForm(request.POST or None, extra=form_fields)
    if form.is_valid():
        # reorder habits
        ans = form.get_answers();
        sorted_ans = sorted(ans.items(), key=operator.itemgetter(1))
        integer_order_ans = []
        for idx, touple in enumerate(sorted_ans):
            habit_id, order = touple
            integer_order_ans.append((habit_id, idx))
        for habit_id, order in integer_order_ans:
            habit = Habit.objects.get(pk=habit_id)
            habit.order = order + 1
            print(habit.order)
            habit.save()
        return HttpResponseRedirect(reverse('tracker:mainpage'))


    # create HabitItems
    habit_items = []
    for habit in habits_list:
        records = get_records_table(habit,DAYS_DISPLAYED)
        computed_speed = get_speed(records)
        hi = HabitItem(
            records_table = records,
            habit= habit,
            speed = computed_speed)
        habit_items.append(hi)

    # create Days to be displayed
    dates = get_dates(DAYS_DISPLAYED)
    future_dates = get_future_dates(FUTURE_DAYS_DISPLAYED)




    # pass the objects
    context = {'habit_items': habit_items,
               'dates': dates,
               'future_dates':future_dates,
               'record_values': RecordValues,
               'username': user.username,
               'new_habits': NEW_HABITS,
               'form':form
               }
    return render(request, 'tracker/mainpage.html', context)


def mainpage_with_styles(request):
    user = request.user

    # get all habits
    habits_list = Habit.objects.filter(user=user).order_by('order')

    # create HabitItems
    habit_items = []
    for habit in habits_list:
        records = get_records_table(habit, DAYS_DISPLAYED)
        computed_speed = get_speed(records)
        hi = HabitItem(
            records_table=records,
            habit=habit,
            speed=computed_speed)
        habit_items.append(hi)

    # create Days to be displayed
    dates = get_dates(DAYS_DISPLAYED)
    future_dates = get_future_dates(FUTURE_DAYS_DISPLAYED)
    # pass the objects
    context = {'habit_items': habit_items,
               'dates': dates,
               'future_dates': future_dates,
               'record_values': RecordValues,
               'username': user.username}
    # return render(request, 'tracker/mainpage_controller.html', context)
    return render(request, 'index_server.html', context)


class HabitItem:
    records_table = []
    habit = None
    speed = 0

    def __init__(self, records_table, habit, speed):
        self.records_table = records_table
        self.habit = habit
        self.speed = speed


class HabitView(generic.DetailView):
    model = Habit
    template_name = 'tracker/habitdetail.html'


def is_author(request, habit):
    if habit.user == request.user:
        return True
    else:
        return False


def can_modify_habit(request, habit_id):
    # find habit or raise 404 error
    habit = get_object_or_404(Habit, pk=habit_id)
    try:
        if habit.user == request.user:
            return True, habit
        else:
            return False, habit
    except(KeyError, Habit.DoesNotExist):
        return False, None


@login_required
def restart_habit_controller(request, habit_id):
    # only author can restart
    can_restart, habit = can_modify_habit(request, habit_id)

tracker/templates/tracker/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
hello from about.html
</body>
</html>

tracker/templates/tracker/add_habit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add habit</title>
</head>
<body>

<p>
    <a href="{% url 'tracker:mainpage' %}">< go to homepage</a>
</p>

<form action="{% url 'tracker:add_habit' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</body>
</html>

tracker/templates/tracker/basetemplate.html
<!DOCTYPE html>
<html lang="en">

<!-- load static url -->
{% load static %}


<!-- head -->
<head>
    <meta charset="UTF-8">
    <title>Habit Tracker - {% block title %}Wellcome!{% endblock %}</title>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta http-equiv="content-language" content="en" />
    <meta name="author" content="Kaisa Halmetoja" />
    <!--<link rel="icon" type="image/png" href="favicon.png"><!---favIkoni--->
    <meta name="keywords" content="WWW design, habit, tracking, habit tracker" />
    <!-- responsiveness to evice size-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Own CSS -->
    <link href="{% static "tracker/index.css" %}" rel="stylesheet" type="text/css" />
    <!-- Icons library-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Bootstrap Core CSS -->
    <link href="{% static "tracker/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Bootstrap JavaScript -->
    <link href="{% static "tracker/js/bootstrap.min.js" %}" rel="script">
</head>


<!-- body -->
<body>
<!-- Header -->
<div class="row" id="navi">
    <div class="col-sm-9">
        <h1 id="hlt" class="page-header"><a href="{% url "tracker:mainpage" %}">Habit Tracker</a>
            <small>teaching you your habits</small>
        </h1>
    </div>
    <div class="col-sm-3">
        {% block link %}{% endblock %}
        <button class="hbutton" id="helpbtn" onclick="document.getElementById('help').style.display='block'"><i class="material-icons" style="font-size:48px;color:#757575;">help</i></button>
    </div>
</div>
<!-- /.row -->


<!-- show login / logout -->
{% block login_register %}
    {% if user.is_authenticated %}
        loged user: {{ username }} <a href="{% url 'users:logout' %}">logout</a>
    {% else %}
        <a href="{% url 'users:login' %}">log in</a>
        <a href="{% url 'users:registration_register' %}">+ register new user</a>
    {% endif %}
    <hr>
{% endblock %}


<!-- render body -->
{% block body %}{% endblock %}


    <!--Modal window for help-->
        <div id="help" class="modal">
            <div class="modal-content animate-zoom">
                <div class="container">
                    <a><span onclick="document.getElementById('help').style.display='none'" class="button.close">X</span></a>
                    <h2>Welcome to Habit Tracker!</h2>
                    <div class="help-text">
                    <p>So you want to establish new habits and turn your life towards better? That’s awesome. <br>
                        We at Habit Tracker want to help you to achieve your goals a bit by bit. Here’s how it works: <br><br>
                    1.	Add a new habit by pushing the red plus mark. We have some suggestions for you, but you can also create your own. <br>Give name to your habit and possibly a duration, like “Meditate for 10 minutes”, and how many times you want to do this per week. <br>Remember, it’s easier to start with small steps! <br><br>
                    2.	Every time you have accomplished one occurrence of the habit, you can mark it down on the habit bar. This way it’s easier for you to follow how you proceed! <br> Next to the bar is a small colorful bar that shows you how you are doing.<br><br>
                    3.	You can see statistics about your habits on the statistics page. </p>
                    </div>
                </div>
            </div>
        </div>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-xs-12">
            <p>Copyright &copy; Habit Tracker 2016</p>
        </div>
    </div>
    <!-- /.row -->
</footer>

<!-- load javascripts -->
<!-- Bootstrap jQuery -->
<script src="{% static "tracker/js/jquery.js" %}"></script>
<!-- Bootstrap Tether -->
<script src="{% static "tracker/js/tether.js" %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static "tracker/js/bootstrap.min.js" %}"></script>
</body>


</html>

tracker/templates/tracker/drop_habit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>droped habit</title>
</head>
<body>

<p>
    {{message}}
</p>
<p>
    <a href="{% url 'tracker:mainpage' %}">< go to homepage</a>
</p>

</body>
</html>

tracker/templates/tracker/edit_habit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit habit</title>
</head>
<body>

<p>
    <a href="{% url 'tracker:mainpage' %}">< go to homepage</a>
</p>
<form action="{% url 'tracker:edit_habit' habit_id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</body>
</html>

tracker/templates/tracker/habitdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Habit - Detail</title>
</head>
<body>

<h1>{{ habit.habit_name }}</h1>
started: {{habit.starting_date}}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% csrf_token %}
<ul>
{% for record in habit.record_set.all %}
    <li>{{ record.date }}</li>
{% endfor %}
</ul>

<p>
    <a href="{% url 'tracker:mainpage' %}">< go to homepage</a>
</p>

</body>
</html>

tracker/templates/tracker/mainpage.html
{% extends 'tracker/basetemplate.html' %}
{% block title %}Habits{% endblock %}
{% block link %}<a href="{% url 'tracker:statistics' %}"><i class="material-icons" style="font-size:48px;color:#757575;">insert_chart</i></a>{% endblock %}
{% block body %}
    {% load mainpage_filters %}
    <!-- load static url -->
    {% load static %}

        {% comment %}<form method="POST" action="{% url 'tracker:mainpage' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type=submit value="Save order">
        </form>{% endcomment %}
        <br>
        <br>
        {% for habit in habit_items %}
            <!-- Habit One -->
            <div class="row">
                <div class="col-xs-2">
                    <!--Habit name-->
                    <a href="{% url 'tracker:edit_habit' habit.habit.id %}"><name>{{ habit|name_formated }}</name></a>
                    <!--Habit progress bar-->
                    <div class="grad">
                        <div class="grad_{{ habit.speed|ratio_to_grad }}">{{habit.speed|ratio_to_percents}}</div>
                    </div>
                </div>
                <div class="col-xs-10">
                    <div class="habitbox">
                        <div class="bar">
                            <table>
                                <tr>
                                    <!-- show dates -->
                                    <!--    for past and today -->
                                    {% for date in dates %}
                                        <th class="date">{{date|date_formated}}</th>
                                    {% endfor%}
                                    <!--    for future -->
                                    {% for date in future_dates %}
                                        <th class="date">{{date|date_formated}}</th>
                                    {% endfor%}
                                </tr>
                                <tr>
                                    <!-- first n days -->
                                    {% for record in habit.records_table %}
                                        <td>
                                            <!-- print record as desired checkbox in desirable state -->
                                            {% if record == record_values.SUCCESS  %}
                                                <a href="{% url 'tracker:edit_record' habit.habit.id forloop.revcounter0 %}">
                                                    <img src='{% static "tracker/check.PNG" %}'/>
{#                                                    <input type="{{ record|render_checkbox }}" checked="{{ record|checkbox_state }}" />#}
                                                </a>
                                            {% else %}
                                                {% if record == record_values.FAIL  %}
                                                    <a href="{% url 'tracker:edit_record' habit.habit.id forloop.revcounter0 %}">
                                                    <img src='{% static "tracker/empty.PNG" %}'/>
{#                                                        <input type="{{ record|render_checkbox }}"/>#}
                                                    </a>
                                                {% else %}
                                                    <!-- display empty column for days before habit started -->
                                                     <img src='{% static "tracker/no-record.png" %}'/>
                                                {% endif %}
                                            {% endif %}
                                        </td>
                                    {% endfor %}

                                    <!-- today -->
                                    <!-- TODO render today differently -->
                                    {# <img src='{% static "tracker/today.png" %}'/> #}

                                    <!-- last four disabled fields -->
                                    {% for date in future_dates %}
                                        <td>
                                            <img src='{% static "tracker/disabled.PNG" %}'/>
                                        </td>
                                    {% endfor%}
                                </tr>
                            </table>
                        </div>
                        <div class="barbuttons">
                            <a href="{% url 'tracker:drop_habit' habit.habit.id %}"><i class="material-icons" style="font-size:28px;color:#e84c3d;">clear</i><br></a>
                            <a href="{% url 'tracker:restart_habit' habit.habit.id %}"><i class="material-icons" style="font-size:28px;color:#e84c3d;">refresh</i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

            <hr>
        {% empty %}
            <p>No habits are available.</p>
        {% endfor %}

    <!-- Add Habit button -->
    <div class="col-xs-12">
{#    Open a pop -up window#}
{#        <button class="hbutton" id="addbtn" onclick="document.getElementById('add').style.display='block'"><i class="material-icons" style="font-size:48px;color:#e84c3d;" >add_circle_outline</i></button>#}
        <!---redirect to add form -->
        <a href="{% url 'tracker:add_habit' %}" >
            <button class="hbutton" id="addbtn"><i class="material-icons" style="font-size:48px;color:#e84c3d;" >add_circle_outline</i></button>
        </a>
    </div>


    {% comment %}
    <!--- debug purposes -->
    <p>
        <a href="{% url 'tracker:add_habit' %}"> + add new</a>
    </p>
    <p>
        <a href="{% url 'tracker:resetdb' %}">reset db</a>
    </p>{% endcomment %}


    <script>
        default_habit = "Do XX for XX minutes";
        habit = default_habit;
    </script>


    <!--Modal window for proposing new habits-->
    <div id="add" class="modal">
        <div class="modal-content animate-zoom">
            <div class="container">
                <a><span onclick="document.getElementById('add').style.display='none'" class="button.close">X</span></a>
                <h2>What new habit would you like to start?</h2>
                <ul>
                    {% for habit in new_habits %}
                        <li>
                            <button class="hbutton"
                                    id = "new_habit_{{ forloop.counter }}"
                                    onclick="document.getElementById('add_habit').style.display='block';
                                             document.getElementById('add').style.display='none';
                                             habit = $(this).text();
                                             document.getElementsByName('new_habit_input')[0].placeholder = habit;
                                             window.location.href = '{% url "tracker:add_habit" %}';
                                            "
                            >
                                <a>{{ habit }}</a>
                            </button></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <!-- Modal window for adding a habit-->
    <div id="add_habit" class="modal">
        <div class="modal-content animate-zoom">
            <div class="container">
                <a><span onclick="document.getElementById('add_habit').style.display='none'" class="button.close">X</span></a>
                <h2>What new habit would you like to start?</h2>
                <div class="new_habit">
                    <label for="habit_name">Habit:</label>
                    <input type="text" class="form-control" placeholder="Do XX for XX minutes" id="habit_name" name="new_habit_input">
                    <label for="occurrences">Times per week:</label>
                    <select class="form-control" id="occurrences">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option selected = "selected">7</option>
                    </select>
                    <br>
                    <div class="modal_buttons">
                        <!--Go back button-->
                        <button class="hbutton" onclick="document.getElementById('add').style.display='block';document.getElementById('add_habit').style.display='none'"><i class="material-icons" style="font-size:36px;color:#e84c3d;" >arrow_back</i></button>
                        <!--Save button-->
                        <button class="hbutton"
                                onclick="document.getElementById('add').style.display='none';
                                         document.getElementById('add_habit').style.display='none';
                                        ">
                            <i class="material-icons" style="font-size:36px;color:#82b940;" >done</i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

tracker/templates/tracker/resetdb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>habits</title>
</head>
<body>

<p>
    {{message}}
</p>
<p>
    <a href="{% url 'tracker:mainpage' %}">< go to homepage</a>
</p>

</body>
</html>

tracker/templates/tracker/restart_habit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>restarted habit</title>
</head>
<body>

<p>
    {{message}}
</p>
<p>
    <a href="{% url 'tracker:mainpage' %}">< go to homepage</a>
</p>

</body>
</html>

tracker/templates/tracker/statistics.html
{% extends 'tracker/basetemplate.html' %}
{% block title %}Statistics{% endblock %}
{% block link %}<a href="{% url 'tracker:mainpage' %}"><i class="material-icons" style="font-size:48px;color:#757575;">home</i></a>{% endblock %}
{% block body %}
    {% load mainpage_filters %}
    Hi {{ username }}, you are doing well with your habits, keep up good work!
    <br>
    <br>
    <!--- columns' descriptions -->
    <!--Name row-->
    <div class="row">
        <div class="col-xs-2">
            <h3>Habit name</h3>
        </div>
        <div class="col-xs-4">
            <h3>Progress bar</h3>
        </div>
        <div class="col-xs-2">
            <h3>Total repetitions</h3>
        </div>
        <div class="col-xs-2">
            <h3>Success %</h3>
        </div>
    </div>

        <!-- show statistics for user's habits -->
        {% for habit in statistics_items %}
            <!-- Habit One -->
            <div class="row">
                <div class="col-xs-2">
                    <h4>{{ habit|name_formated }}</h4>
                </div>
                <div class="col-xs-4">
                    <div class="statusbar" id="statgrad1">
                        <div class="grad_good percentage-{{ habit.last_10_days_success_ratio|ratio_to_percents_not_formated }}"></div>{{ habit.last_10_days_success_ratio|ratio_to_percents }}
                    </div>
                </div>
                <div class="col-xs-2">
                    <h4>{{ habit.total_sucesses }} in {{ habit.time_since_start|format_days_elapsed }}</h4>
                </div>
                <div class="col-xs-2">
                    <h4>{{ habit.overall_sucess_ratio|ratio_to_percents }}</h4>
                </div>
            </div>
            <!-- /.row -->

            <hr>
        {% empty %}
            <!-- user has no habits -->
        <div class="row">
            <div class="col-xs-2">
                <h4>No habits for statistics are available.</h4>
            </div>
            <div class="col-xs-4">

            </div>
            <div class="col-xs-2">

            </div>
            <div class="col-xs-2">

            </div>
        </div>
        <!-- /.row -->
        {% endfor %}

{% endblock %}